import React from 'react';
import { Metadata } from 'next';
import Section from '@/components/ui/Section';
import BackToHome from '@/components/ui/BackToHome';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Understand how Xenolyth collects, processes, and secures telemetric data and autonomous decision logs.',
};

export default function PrivacyPage() {
  return (
    <div className="relative w-full bg-bg-primary min-h-screen">
      <Section id="privacy-header" className="pt-28 pb-8">
        <div className="max-w-[800px] flex flex-col gap-4">
          <BackToHome />
          <span className="label-eyebrow text-accent font-semibold tracking-widest">
            Privacy Policy
          </span>
          <h1 className="h1-heading text-text-primary tracking-tight font-bold">
            Platform Privacy Policy
          </h1>
        </div>
      </Section>

      <Section id="privacy-content" bg="secondary" className="py-16">
        <div className="max-w-[760px] mx-auto text-left flex flex-col gap-8 text-sm text-text-secondary leading-relaxed">
          <div className="flex flex-col gap-3">
            <h2 className="text-base font-semibold text-text-primary">1. Telemetry and State Collection</h2>
            <p>
              To execute autonomous guardrails and coordinate threat mitigations, Xenolyth local binaries collect state indicators from host instances. This telemetry includes network port mappings, CPU utilization baseline averages, and local process list summaries.
            </p>
            <p>
              This telemetry is processed locally on your host machines by default. Only encrypted metadata summaries are transmitted to Xenolyth servers to populate dashboard analytics.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-base font-semibold text-text-primary">2. Decision and Reasoning Log Storage</h2>
            <p>
              Decision logs generated by Sentinel and Argus agents are stored in structured, read-only system files on your infrastructure. These logs contain the telemetric signals that triggered action, the logical rules satisfied, and the timestamp records of the intervention.
            </p>
            <p>
              We do not transmit complete payload contents, network packets, or server variables to our databases. Your intellectual property and data assets remain within your secure network perimeter.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-base font-semibold text-text-primary">3. Cryptographic Security and Auditing</h2>
            <p>
              Xenolyth secures transmitted metadata using Transport Layer Security (TLS 1.3). Access to telemetry dashboards requires multi-factor authentication, and permission tokens are signed using cryptographic private keys.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-base font-semibold text-text-primary">4. Data Deletion and Policy Audits</h2>
            <p>
              You may initiate a deletion of all historical console metadata at any time. Because local decision logs are stored on your assets, you retain complete authority over their deletion schedule, file format, and long-term storage configurations.
            </p>
          </div>
        </div>
      </Section>
    </div>
  );
}
